/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Fri, 17 Jan 2025 16:29:43 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.ts3enum.gfx;

import waffleoRai_DataContainers.EnumStringMapper32;

public class Shader {
//Game Script: 
//Enum type: u32

	public static final int None = 0x00000000;
	public static final int Additive = 0x5af16731;
	public static final int BasinWater = 0x6aad2ad5;
	public static final int Blueprint = 0x6864a45e;
	public static final int BuildingWindow = 0x7b036c01;
	public static final int CASRoom = 0x94b9a835;
	public static final int Counters = 0xa4172f62;
	public static final int DropShadow = 0xc09c7582;
	public static final int Fence = 0x67107fe8;
	public static final int FlatMirror = 0xa68d9e29;
	public static final int Floors = 0xbc84d000;
	public static final int Foliage = 0x4549e22e;
	public static final int FullBright = 0x14fa335e;
	public static final int Gemstones = 0xa063c1d0;
	public static final int GlassForFences = 0x52986c62;
	public static final int GlassForObjects = 0x492eca7c;
	public static final int GlassForObjectsTranslucent = 0x849cf021;
	public static final int GlassForPortals = 0x81dd204d;
	public static final int GlassForRabbitHoles = 0x265ffaa1;
	public static final int ImpostorWater = 0x277cf8eb;
	public static final int Instanced = 0x0cb82eb8;
	public static final int Landmark = 0x8a60b969;
	public static final int LotImposter = 0x68601de3;
	public static final int OutdoorProp = 0x4d26bec0;
	public static final int Painting = 0xaa495821;
	public static final int ParticleAnim = 0x460e93f4;
	public static final int ParticleJet = 0xff5e6908;
	public static final int Phong = 0xb9105a6d;
	public static final int PhongAlpha = 0xfc5fc212;
	public static final int Plumbob = 0xdef16564;
	public static final int PreviewWallsAndFloors = 0x213d6300;
	public static final int RabbitHoleHighDetail = 0x8d346bbc;
	public static final int RabbitHoleMediumDetail = 0xaede7105;
	public static final int Roof = 0x7bd05f63;
	public static final int Rug = 0x2a72b9a1;
	public static final int SculptureIce = 0xe5d98507;
	public static final int ShadowMap = 0x21fe207d;
	public static final int SimEyelashes = 0x9d9da161;
	public static final int SimEyes = 0xcf8a70b4;
	public static final int Simglass = 0x5eda9cde;
	public static final int SimHair = 0x84fd7152;
	public static final int SimSkin = 0x548394b9;
	public static final int SolidPhong = 0x47c6638c;
	public static final int Stairs = 0x4ce2f497;
	public static final int StandingWater = 0x70fde012;
	public static final int Subtractive = 0x0b272cc5;
	public static final int Trampoline = 0x3939e094;

	public static final int[] ALL_VALUES = {
		0x00000000, 0x5af16731, 0x6aad2ad5, 0x6864a45e, 0x7b036c01, 0x94b9a835, 0xa4172f62, 0xc09c7582, 
		0x67107fe8, 0xa68d9e29, 0xbc84d000, 0x4549e22e, 0x14fa335e, 0xa063c1d0, 0x52986c62, 0x492eca7c, 
		0x849cf021, 0x81dd204d, 0x265ffaa1, 0x277cf8eb, 0x0cb82eb8, 0x8a60b969, 0x68601de3, 0x4d26bec0, 
		0xaa495821, 0x460e93f4, 0xff5e6908, 0xb9105a6d, 0xfc5fc212, 0xdef16564, 0x213d6300, 0x8d346bbc, 
		0xaede7105, 0x7bd05f63, 0x2a72b9a1, 0xe5d98507, 0x21fe207d, 0x9d9da161, 0xcf8a70b4, 0x5eda9cde, 
		0x84fd7152, 0x548394b9, 0x47c6638c, 0x4ce2f497, 0x70fde012, 0x0b272cc5, 0x3939e094
	};

	public static final String[] ALL_NAMES = {
		"None", "Additive", "BasinWater", "Blueprint", 
		"BuildingWindow", "CASRoom", "Counters", "DropShadow", 
		"Fence", "FlatMirror", "Floors", "Foliage", 
		"FullBright", "Gemstones", "GlassForFences", "GlassForObjects", 
		"GlassForObjectsTranslucent", "GlassForPortals", "GlassForRabbitHoles", "ImpostorWater", 
		"Instanced", "Landmark", "LotImposter", "OutdoorProp", 
		"Painting", "ParticleAnim", "ParticleJet", "Phong", 
		"PhongAlpha", "Plumbob", "PreviewWallsAndFloors", "RabbitHoleHighDetail", 
		"RabbitHoleMediumDetail", "Roof", "Rug", "SculptureIce", 
		"ShadowMap", "SimEyelashes", "SimEyes", "Simglass", 
		"SimHair", "SimSkin", "SolidPhong", "Stairs", 
		"StandingWater", "Subtractive", "Trampoline"
	};

	private static EnumStringMapper32 mapper;

	public static String stringFromValue(int value){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValue(value);
	}

	public static int valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromString(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
