/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Fri, 17 Jan 2025 16:29:43 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.ts3enum.gfx;

import waffleoRai_DataContainers.EnumStringMapper32;

public class TxtcStepTypes {
//Game Script: 
//Enum type: u32

	public static final int DrawFabric = 0x034210A5;
	public static final int ChannelSelect = 0x1E363B9B;
	public static final int SkinTone = 0x43B554E3;
	public static final int HairTone = 0x5D7C85D4;
	public static final int RemappedChannelSelect = 0x890805DB;
	public static final int ColorFill = 0x9CD1269D;
	public static final int DrawImage = 0xA15200B1;
	public static final int CASPickData = 0xC6B6AC1F;
	public static final int SetTarget = 0xD6BD8695;
	public static final int HSV2RGB = 0xDC0984B9;

	public static final int[] ALL_VALUES = {
		0x034210A5, 0x1E363B9B, 0x43B554E3, 0x5D7C85D4, 0x890805DB, 0x9CD1269D, 0xA15200B1, 0xC6B6AC1F, 
		0xD6BD8695, 0xDC0984B9
	};

	public static final String[] ALL_NAMES = {
		"DrawFabric", "ChannelSelect", "SkinTone", "HairTone", 
		"RemappedChannelSelect", "ColorFill", "DrawImage", "CASPickData", 
		"SetTarget", "HSV2RGB"
	};

	private static EnumStringMapper32 mapper;

	public static String stringFromValue(int value){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValue(value);
	}

	public static int valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromString(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
