/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Wed, 1 Jan 2025 13:25:33 -0600
 *-----------------------------------------------------*/

package waffleoRai_Containers.maxis.ts3.savefmts.travel;

import java.util.Map;
import java.util.HashMap;

public class CollectableRelicGuid {
//Game Script: 
//Enum type: u32

	public static final int CanopicJarA = 0x08927036;
	public static final int CanopicJarB = 0x0892703A;
	public static final int CanopicJarC = 0x0892703E;
	public static final int CanopicJarD = 0x08927043;
	public static final int CanopicJarE = 0x08927047;
	public static final int Cobra = 0x0892704B;
	public static final int Horus = 0x0892704F;
	public static final int Sphynx = 0x08927055;
	public static final int Seth = 0x0892705B;
	public static final int Dragon = 0x08927062;
	public static final int Snake = 0x08927068;
	public static final int Tiger = 0x0892706D;
	public static final int TexturedVase1 = 0x08927071;
	public static final int TexturedVase1A = 0x08927074;
	public static final int TexturedVase1B = 0x08927078;
	public static final int TexturedVase1C = 0x0892707B;
	public static final int TexturedVase2 = 0x08927080;
	public static final int TexturedVase2A = 0x08927083;
	public static final int TexturedVase2B = 0x08927087;
	public static final int TexturedVase2C = 0x0892708A;
	public static final int AmmittheDestroyer = 0x0892708D;
	public static final int Anubis = 0x08927091;
	public static final int FuDog = 0x08927094;
	public static final int Gargoyle = 0x08927098;
	public static final int DropaStone = 0x0892709B;
	public static final int DropaStoneA = 0x0892709F;
	public static final int DropaStoneB = 0x089270A3;
	public static final int DropaStoneC = 0x089270A6;
	public static final int DropaStoneD = 0x089270A9;
	public static final int DropaStoneE = 0x089270AD;
	public static final int TombofDiscovery = 0x08C0EECA;
	public static final int TomboftheBurningSands = 0x08C0EECE;
	public static final int TomboftheRock = 0x08C0EED2;
	public static final int TomboftheDesertOcean = 0x08C0EED5;
	public static final int CriminalHQ = 0x08C0EED8;
	public static final int AncientLibrary = 0x08C0EEDC;
	public static final int CommandCenter = 0x08C0EEE0;
	public static final int SoulpeaceChambers = 0x08C0EEE3;
	public static final int HatshepsutsQuarters = 0x08C0EEE7;
	public static final int BazaarTomb = 0x08C0EEEB;
	public static final int TempleofDeath = 0x08C0EEEE;
	public static final int TomboftheInifiteHalls = 0x08C0EEF1;
	public static final int CopperQuarry = 0x08C0EEF6;
	public static final int KarnakTreasureHalls = 0x08C0EEF9;
	public static final int SanctuaryofHorus = 0x08C0EEFD;
	public static final int TempleoftheAxe = 0x08C0EF00;
	public static final int ResoluteFistAnnex = 0x08C0EF04;
	public static final int TomboftheDragonEmperor = 0x08C0EF06;
	public static final int DragonCave = 0x08C0EF0A;
	public static final int RicePaddyHiddenTemple = 0x08C0EF0D;
	public static final int HotSpringsHiddenTemple = 0x08C0EF10;
	public static final int DongHuoTreasureTrove = 0x08C0EF14;
	public static final int MarketCaves = 0x08C0EF18;
	public static final int AncientMonkRetreat = 0x08C0EF1C;
	public static final int NectarCatacombs = 0x08C0EF20;
	public static final int TombofIsael = 0x08C0EF24;
	public static final int TombofNecteaux = 0x08C0EF2F;
	public static final int LouvreCatacombs = 0x08C0EF35;
	public static final int TombofFerrisonHord = 0x08C0EF39;
	public static final int FaerieTomb = 0x08C0EF3D;
	public static final int CelticBurialSite = 0x08C0EF41;
	public static final int CelticBurialSitePangu = 0x08C0EF44;
	public static final int CelticBurialSiteFloorPanel = 0x08C0EF47;
	public static final int FakeTombofNecteauxThief = 0x08C0EF4A;
	public static final int FakeTombofNecteauxThug = 0x08C0EF4D;
	public static final int ChateauduLandgraab = 0x08C0EF50;
	public static final int InvalidGuid = 0xFFFFFFFF;

	public static final int[] ALL_VALUES = {
		0x08927036, 0x0892703A, 0x0892703E, 0x08927043, 0x08927047, 0x0892704B, 0x0892704F, 0x08927055, 
		0x0892705B, 0x08927062, 0x08927068, 0x0892706D, 0x08927071, 0x08927074, 0x08927078, 0x0892707B, 
		0x08927080, 0x08927083, 0x08927087, 0x0892708A, 0x0892708D, 0x08927091, 0x08927094, 0x08927098, 
		0x0892709B, 0x0892709F, 0x089270A3, 0x089270A6, 0x089270A9, 0x089270AD, 0x08C0EECA, 0x08C0EECE, 
		0x08C0EED2, 0x08C0EED5, 0x08C0EED8, 0x08C0EEDC, 0x08C0EEE0, 0x08C0EEE3, 0x08C0EEE7, 0x08C0EEEB, 
		0x08C0EEEE, 0x08C0EEF1, 0x08C0EEF6, 0x08C0EEF9, 0x08C0EEFD, 0x08C0EF00, 0x08C0EF04, 0x08C0EF06, 
		0x08C0EF0A, 0x08C0EF0D, 0x08C0EF10, 0x08C0EF14, 0x08C0EF18, 0x08C0EF1C, 0x08C0EF20, 0x08C0EF24, 
		0x08C0EF2F, 0x08C0EF35, 0x08C0EF39, 0x08C0EF3D, 0x08C0EF41, 0x08C0EF44, 0x08C0EF47, 0x08C0EF4A, 
		0x08C0EF4D, 0x08C0EF50, 0xFFFFFFFF
	};

	public static final String[] ALL_NAMES = {
		"CanopicJarA", "CanopicJarB", "CanopicJarC", "CanopicJarD", 
		"CanopicJarE", "Cobra", "Horus", "Sphynx", 
		"Seth", "Dragon", "Snake", "Tiger", 
		"TexturedVase1", "TexturedVase1A", "TexturedVase1B", "TexturedVase1C", 
		"TexturedVase2", "TexturedVase2A", "TexturedVase2B", "TexturedVase2C", 
		"AmmittheDestroyer", "Anubis", "FuDog", "Gargoyle", 
		"DropaStone", "DropaStoneA", "DropaStoneB", "DropaStoneC", 
		"DropaStoneD", "DropaStoneE", "TombofDiscovery", "TomboftheBurningSands", 
		"TomboftheRock", "TomboftheDesertOcean", "CriminalHQ", "AncientLibrary", 
		"CommandCenter", "SoulpeaceChambers", "HatshepsutsQuarters", "BazaarTomb", 
		"TempleofDeath", "TomboftheInifiteHalls", "CopperQuarry", "KarnakTreasureHalls", 
		"SanctuaryofHorus", "TempleoftheAxe", "ResoluteFistAnnex", "TomboftheDragonEmperor", 
		"DragonCave", "RicePaddyHiddenTemple", "HotSpringsHiddenTemple", "DongHuoTreasureTrove", 
		"MarketCaves", "AncientMonkRetreat", "NectarCatacombs", "TombofIsael", 
		"TombofNecteaux", "LouvreCatacombs", "TombofFerrisonHord", "FaerieTomb", 
		"CelticBurialSite", "CelticBurialSitePangu", "CelticBurialSiteFloorPanel", "FakeTombofNecteauxThief", 
		"FakeTombofNecteauxThug", "ChateauduLandgraab", "InvalidGuid"
	};

	private static Map<String, Integer> nameMap;
	private static Map<Integer, String> valMap;

	public static String stringFromValue(int value){
		if(valMap == null){
			valMap = new HashMap<Integer, String>();
			for(int i = 0; i < ALL_VALUES.length; i++){
				valMap.put(ALL_VALUES[i], ALL_NAMES[i]);
			}
		}
		return valMap.get(value);
	}

	public static int valueFromString(String str){
		if(nameMap == null){
			nameMap = new HashMap<String, Integer>();
			for(int i = 0; i < ALL_NAMES.length; i++){
				nameMap.put(ALL_NAMES[i], ALL_VALUES[i]);
			}
		}
		Integer mappedVal = nameMap.get(str);
		if(mappedVal == null) return -1;
		return mappedVal;
	}

	public static void disposeMaps(){
		if(nameMap != null){
			nameMap.clear();
			nameMap = null;
		}
		if(valMap != null){
			valMap.clear();
			valMap = null;
		}
	}
}
