/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Wed, 1 Jan 2025 17:51:25 -0600
 *-----------------------------------------------------*/

package waffleoRai_Containers.maxis.ts3.savefmts.travel;

import waffleoRai_DataContainers.EnumStringMapper64;

public class UniqueObjectKey {
//Game Script: Sims3.Gameplay.Abstracts.UniqueObjectKey
//Enum type: u64

	public static final long None = 0x00000000L;
	public static final long LeftEyeOfHorus = 0x00000001L;
	public static final long RightEyeOfHorus = 0x00000004L;
	public static final long PanguAxe = 0x00000008L;

	public static final long[] ALL_VALUES = {
		0x00000000L, 0x00000001L, 0x00000004L, 0x00000008L
	};

	public static final String[] ALL_NAMES = {
		"None", "LeftEyeOfHorus", "RightEyeOfHorus", "PanguAxe"
	};

	private static EnumStringMapper64 mapper;

	public static String stringFromValue(long value){
		if(mapper == null){
			mapper = new EnumStringMapper64(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValueFlags(value);
	}

	public static long valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper64(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromStringFlags(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
