/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Sat, 18 Jan 2025 20:14:47 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.ts3enum.cas;

import waffleoRai_DataContainers.EnumStringMapper32;

public class CASGeomFlags {
//Game Script: 
//Enum type: u32

	public static final int Mergable = 0x00000001;
	public static final int IncludeMorphs = 0x00000002;
	public static final int IncludeTweaks = 0x00000004;
	public static final int IncludeTangents = 0x00000008;
	public static final int FourBoneSkinning = 0x00000010;
	public static final int TwoBoneSkinning = 0x00000020;
	public static final int TwoQuatSkinning = 0x00000040;
	public static final int OneQuatSkinning = 0x00000080;
	public static final int SpecLevel0 = 0x00000100;
	public static final int SpecLevel1 = 0x00000200;
	public static final int SpecLevel2 = 0x00000400;
	public static final int SpecLevel3 = 0x00000800;
	public static final int SpecLevel4 = 0x00001000;
	public static final int SpecLevel5 = 0x00002000;
	public static final int Sorted = 0x00004000;
	public static final int ShadowCaster = 0x00008000;

	public static final int[] ALL_VALUES = {
		0x00000001, 0x00000002, 0x00000004, 0x00000008, 0x00000010, 0x00000020, 0x00000040, 0x00000080, 
		0x00000100, 0x00000200, 0x00000400, 0x00000800, 0x00001000, 0x00002000, 0x00004000, 0x00008000
	};

	public static final String[] ALL_NAMES = {
		"Mergable", "IncludeMorphs", "IncludeTweaks", "IncludeTangents", 
		"FourBoneSkinning", "TwoBoneSkinning", "TwoQuatSkinning", "OneQuatSkinning", 
		"SpecLevel0", "SpecLevel1", "SpecLevel2", "SpecLevel3", 
		"SpecLevel4", "SpecLevel5", "Sorted", "ShadowCaster"
	};

	private static EnumStringMapper32 mapper;

	public static String stringFromValue(int value){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValueFlags(value);
	}

	public static int valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromStringFlags(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
