/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Sat, 18 Jan 2025 20:14:47 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.ts3enum.cas;

import waffleoRai_DataContainers.EnumStringMapper32;

public class CASPartType {
//Game Script: 
//Enum type: u32

	public static final int Hair = 0x00000001;
	public static final int Scalp = 0x00000002;
	public static final int FaceOverlay = 0x00000004;
	public static final int Body = 0x00000008;
	public static final int Accessory = 0x00000010;

	public static final int[] ALL_VALUES = {
		0x00000001, 0x00000002, 0x00000004, 0x00000008, 0x00000010
	};

	public static final String[] ALL_NAMES = {
		"Hair", "Scalp", "FaceOverlay", "Body", 
		"Accessory"
	};

	private static EnumStringMapper32 mapper;

	public static String stringFromValue(int value){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValueFlags(value);
	}

	public static int valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromStringFlags(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
