/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Tue, 31 Dec 2024 21:11:27 -0600
 *-----------------------------------------------------*/

//Last check pass: 2025/01/01 19:10

package waffleoRai_Files.maxis.ts3save.career;

import java.io.IOException;
import java.io.Writer;

import org.w3c.dom.Element;

import waffleoRai_Containers.maxis.MaxisPropertyStream;
import waffleoRai_Files.XMLReader;
import waffleoRai_Files.maxis.ts3save.TS3Saveable;
import waffleoRai_Utils.BufferReference;
import waffleoRai_Utils.FileBuffer;
import waffleoRai_Utils.StringUtils;

public class JobContent extends TS3Saveable{
//TS3 Script: Sims3.Gameplay.Careers.CareerManager

	public static final int PSID_GUID = 0xAE293BA5;
	public static final int PSID_JOB = 0x00000000;

	private static final String XMLKEY_GUID = "Guid";
	private static final String XMLKEY_JOB = "Job";

	public long guid;
	public Occupation job;

	public JobContent() {
		xmlNodeName = "JobContent";
		baseSize = 8;
	}
	
	/*----- Read -----*/
	
	protected boolean readBinary_internal(BufferReference dat) {
		if(dat == null) return false;
		
		guid = dat.nextLong();
		job = Occupation.readBinary(dat);

		return true;
	}
	
	protected boolean readXMLNode_internal(Element xml_element) {
		if(xml_element == null) return false;
		String nn = xml_element.getNodeName();
		if(nn == null) return false;
		if(!nn.equals(xmlNodeName)) return false;
		
		String aval = null;
		Element child = null;
		aval = xml_element.getAttribute(XMLKEY_GUID);
		if(aval != null) guid = StringUtils.parseUnsignedLong(aval);
		child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "Occupation", "VarName", XMLKEY_JOB);
		if(child != null) job = Occupation.readXMLNode(child);

		return true;
	}
	
	protected boolean readPropertyStream_internal(MaxisPropertyStream stream) {
		if(stream == null) return false;
		guid = stream.getFieldAsLong(PSID_GUID, false);
		job = Occupation.readPropertyStream(stream); //Same stream
		return true;
	}
	
	public static JobContent readBinary(BufferReference dat) {
		if(dat == null) return null;
		JobContent str = new JobContent();
		if(!str.readBinary_internal(dat)) return null;
		return str;
	}
	
	public static JobContent readXMLNode(Element xml_element) {
		if(xml_element == null) return null;
		JobContent str = new JobContent();
		if(!str.readXMLNode_internal(xml_element)) return null;
		return str;
	}
	
	public static JobContent readPropertyStream(BufferReference dat, boolean byteOrder, int verFieldSize) {
		if(dat == null) return null;
		MaxisPropertyStream stream = MaxisPropertyStream.openForRead(dat, byteOrder, verFieldSize);
		return readPropertyStream(stream);
	}
	
	public static JobContent readPropertyStream(MaxisPropertyStream stream) {
		if(stream == null) return null;
		JobContent str = new JobContent();
		if(!str.readPropertyStream_internal(stream));
		return str;
	}
	
	/*----- Write -----*/
	
	public int getBinarySize() {
		int size = baseSize;
		if(job != null) size += job.getBinarySize();
		return size;
	}
	
	public FileBuffer writeBinary(boolean byteOrder) {
		FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
		writeBinaryTo(buff);
		return buff;
	}
	
	public int writeBinaryTo(FileBuffer target) {
		if(target == null) return 0;
		long stPos = target.getFileSize();
		
		target.addToFile(guid);
		job.writeBinaryTo(target);

		return (int)(target.getFileSize() - stPos);
	}

	public void writeXMLNode(Writer out, String indent) throws IOException {
		writeXMLNode(out, indent, null);
	}
	
	public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
		if(out == null) return;
		if(indent == null) indent = "";
		
		out.write(indent);
		out.write(String.format("<%s", xmlNodeName));
		if(varName != null){
			out.write(String.format(" VarName=\"%s\"", varName));
		}
		out.write(String.format(" %s=\"0x%016x\"", XMLKEY_GUID, guid));
		out.write(">\n");
		if(job != null) job.writeXMLNode(out, indent + "\t", XMLKEY_JOB);
		out.write(indent);
		out.write(String.format("</%s>\n", xmlNodeName));

	}

	public void addToPropertyStream(MaxisPropertyStream ps) {	
		if(ps == null) return;
		ps.addLong(guid, PSID_GUID, false);
		job.addToPropertyStream(ps); //Same stream
	}
	
}
