/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Tue, 31 Dec 2024 21:11:14 -0600
 *-----------------------------------------------------*/

package waffleoRai_Containers.maxis.ts3.savefmts.career;

import java.util.Map;
import java.util.HashMap;

public class AcademicDegreeNames {
//Game Script: Sims3.Gameplay.Academics.AcademicDegreeNames
//Enum type: u64

	public static final long Undefined = 0x00L;
	public static final long Business = 0x01L;
	public static final long Technology = 0x02L;
	public static final long Science = 0x03L;
	public static final long FineArts = 0x04L;
	public static final long Communications = 0x05L;
	public static final long PhysEd = 0x06L;
	public static final long MaxDegreeNames = 0x07L;

	public static final long[] ALL_VALUES = {
		0x00L, 0x01L, 0x02L, 0x03L, 
		0x04L, 0x05L, 0x06L, 0x07L
	};

	public static final String[] ALL_NAMES = {
		"Undefined", "Business", "Technology", "Science", 
		"FineArts", "Communications", "PhysEd", "MaxDegreeNames"
	};

	private static Map<String, Long> nameMap;
	private static Map<Long, String> valMap;

	public static String stringFromValue(long value){
		if(valMap == null){
			valMap = new HashMap<Long, String>();
			for(int i = 0; i < ALL_VALUES.length; i++){
				valMap.put(ALL_VALUES[i], ALL_NAMES[i]);
			}
		}
		return valMap.get(value);
	}

	public static long valueFromString(String str){
		if(nameMap == null){
			nameMap = new HashMap<String, Long>();
			for(int i = 0; i < ALL_NAMES.length; i++){
				nameMap.put(ALL_NAMES[i], ALL_VALUES[i]);
			}
		}
		Long mappedVal = nameMap.get(str);
		if(mappedVal == null) return -1L;
		return mappedVal;
	}

	public static void disposeMaps(){
		if(nameMap != null){
			nameMap.clear();
			nameMap = null;
		}
		if(valMap != null){
			valMap.clear();
			valMap = null;
		}
	}
}
