/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Fri, 17 Jan 2025 20:01:27 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.res.gfx;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;

import org.w3c.dom.Element;

import waffleoRai_Containers.maxis.MaxisTypes;
import waffleoRai_Files.XMLReader;
import waffleoRai_Utils.BufferReference;
import waffleoRai_Utils.FileBuffer;
import waffleoRai_Utils.StringUtils;

public class BONEResource{

	private static final String XMLKEY_FILEVERSION = "FileVersion";
	//private static final String XMLKEY_BONENAMECOUNT = "BoneNameCount";
	private static final String XMLKEY_BONENAMETABLE = "BoneNameTable";
	//private static final String XMLKEY_BONEMATRIXCOUNT = "BoneMatrixCount";
	private static final String XMLKEY_BONEMATRIXTABLE = "BoneMatrixTable";

	public int fileVersion;
	public int boneNameCount;
	public ArrayList<String> boneNameTable = new ArrayList<String>();
	public int boneMatrixCount;
	public ArrayList<float[]> boneMatrixTable = new ArrayList<float[]>();

	private String xmlNodeName;
	private int baseSize;

	public BONEResource() {
		xmlNodeName = "BONEResource";
		baseSize = 12;
	}
	
	/*----- Read -----*/
	
	protected boolean readBinary_internal(BufferReference dat) {
		if(dat == null) return false;
		
		fileVersion = dat.nextInt();
		boneNameCount = dat.nextInt();
		boneNameTable.ensureCapacity(boneNameCount);
		for(int i = 0; i < boneNameCount; i++){
			String boneName = MaxisTypes.readMaxis7String(dat);
			if(boneName != null) boneNameTable.add(boneName);
		}
		boneMatrixCount = dat.nextInt();
		boneMatrixTable.ensureCapacity(boneMatrixCount);
		for(int i = 0; i < boneMatrixCount; i++){
			float[] boneMtx = new float[12];
			for(int j = 0; j < 12; j++) {
				boneMtx[j] = Float.intBitsToFloat(dat.nextInt());
			}
			boneMatrixTable.add(boneMtx);
		}

		return true;
	}
	
	protected boolean readXMLNode_internal(Element xml_element) {
		if(xml_element == null) return false;
		String nn = xml_element.getNodeName();
		if(nn == null) return false;
		if(!nn.equals(xmlNodeName)) return false;
		
		String aval = null;
		Element child = null;
		aval = xml_element.getAttribute(XMLKEY_FILEVERSION);
		if(aval != null) fileVersion = StringUtils.parseSignedInt(aval);
		//aval = xml_element.getAttribute(XMLKEY_BONENAMECOUNT);
		//if(aval != null) boneNameCount = StringUtils.parseSignedInt(aval);
		child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "List", "VarName", XMLKEY_BONENAMETABLE);
		if(child != null){
			List<Element> gclist = XMLReader.getChildElementsWithTag(child, "ListMember");
			boneNameCount = gclist.size();
			boneNameTable.ensureCapacity(boneNameCount);
			
			if(boneNameCount > 0) {
				for(Element gc : gclist){
					aval = gc.getAttribute("Value");
					boneNameTable.add(aval);
				}	
			}
		}
		//aval = xml_element.getAttribute(XMLKEY_BONEMATRIXCOUNT);
		//if(aval != null) boneMatrixCount = StringUtils.parseSignedInt(aval);
		child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "List", "VarName", XMLKEY_BONEMATRIXTABLE);
		if(child != null){
			List<Element> gclist = XMLReader.getChildElementsWithTag(child, "ListMember");
			boneMatrixCount = gclist.size();
			boneMatrixTable.ensureCapacity(boneMatrixCount);
			if(boneMatrixCount > 0) {
				for(Element gc : gclist){
					aval = gc.getAttribute("Value");
					if(!aval.isEmpty()) {
						aval = aval.replace("{", "");
						aval = aval.replace("}", "");
						String[] spl = aval.split(",");
						float[] mtx = new float[12];
						for(int j = 0; j < 12; j++) {
							if(j >= spl.length) break;
							mtx[j] = (float)Double.parseDouble(spl[j].trim());
						}
					}
					else boneMatrixTable.add(new float[12]);
				}	
			}
		}

		return true;
	}
	
	public static BONEResource readBinary(BufferReference dat) {
		if(dat == null) return null;
		BONEResource str = new BONEResource();
		if(!str.readBinary_internal(dat)) return null;
		return str;
	}
	
	public static BONEResource readXMLNode(Element xml_element) {
		if(xml_element == null) return null;
		BONEResource str = new BONEResource();
		if(!str.readXMLNode_internal(xml_element)) return null;
		return str;
	}
	
	/*----- Write -----*/
	
	public int getBinarySize() {
		int size = baseSize;
		size += boneNameTable.size(); //String length bytes
		for(String boneName : boneNameTable){
			size += (boneName.length() << 1);
		}
		size += boneMatrixTable.size() * 48;
		return size;
	}
	
	public FileBuffer writeBinary(boolean byteOrder) {
		FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
		writeBinaryTo(buff);
		return buff;
	}
	
	public int writeBinaryTo(FileBuffer target) {
		if(target == null) return 0;
		long stPos = target.getFileSize();
		
		boneNameCount = boneNameTable.size();
		boneMatrixCount = boneMatrixTable.size();
		target.addToFile(fileVersion);
		target.addToFile(boneNameCount);
		for(String boneName : boneNameTable){
			MaxisTypes.serializeMaxis7StringTo(boneName, target);
		}
		target.addToFile(boneMatrixCount);
		for(float[] boneMatrix : boneMatrixTable){
			for(int j = 0; j < 12; j++) {
				target.addToFile(Float.floatToRawIntBits(boneMatrix[j]));
			}
		}

		return (int)(target.getFileSize() - stPos);
	}

	public void writeXMLNode(Writer out, String indent) throws IOException {
		writeXMLNode(out, indent, null);
	}
	
	public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
		if(out == null) return;
		if(indent == null) indent = "";
		
		boneNameCount = boneNameTable.size();
		boneMatrixCount = boneMatrixTable.size();
		out.write(indent);
		out.write(String.format("<%s", xmlNodeName));
		if(varName != null){
			out.write(String.format(" VarName=\"%s\"", varName));
		}
		out.write(String.format(" %s=\"%d\"", XMLKEY_FILEVERSION, fileVersion));
		//out.write(String.format(" %s=\"%d\"", XMLKEY_BONENAMECOUNT, boneNameCount));
		//out.write(String.format(" %s=\"%d\"", XMLKEY_BONEMATRIXCOUNT, boneMatrixCount));
		out.write(">\n");
		out.write(indent + "\t<List ");
		out.write(String.format(" VarName=\"%s\">\n", XMLKEY_BONENAMETABLE));
		for(String boneName : boneNameTable){
			out.write(indent + String.format("\t\t<ListMember Value=\"%s\"/>\n", boneName));
		}
		out.write(indent + "\t</List>\n");
		
		out.write(indent + "\t<List ");
		out.write(String.format(" VarName=\"%s\">\n", XMLKEY_BONEMATRIXTABLE));
		for(float[] boneMatrix : boneMatrixTable){
			out.write(indent + String.format("\t\t<ListMember Value=\"{"));
			for(int j = 0; j < 12; j++) {
				if(j > 0) out.write(",");
				out.write(String.format("%.4f", boneMatrix[j]));
			}
			out.write("}\"/>\n");
		}
		out.write(indent + "\t</List>\n");
		out.write(indent);
		out.write(String.format("</%s>\n", xmlNodeName));
	}

}
