/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Sat, 18 Jan 2025 20:48:45 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.res.gfx;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;

import org.w3c.dom.Element;

import waffleoRai_Files.XMLReader;
import waffleoRai_Utils.BufferReference;
import waffleoRai_Utils.FileBuffer;
import waffleoRai_Utils.StringUtils;

public class BoneDeltaRes{

	private static final String XMLKEY_FILEVERSION = "FileVersion";
	//private static final String XMLKEY_ENTRYCOUNT = "EntryCount";
	private static final String XMLKEY_ENTRIES = "Entries";

	public int fileVersion;
	public int entryCount;
	public ArrayList<BoneDelta> entries = new ArrayList<BoneDelta>();

	private String xmlNodeName;
	private int baseSize;

	public BoneDeltaRes() {
		xmlNodeName = "BoneDeltaRes";
		baseSize = 8;
	}
	
	/*----- Inner Classes -----*/

	public static class BoneDelta{

	
		private static final String XMLKEY_SLOTHASH = "SlotHash";
		private static final String XMLKEY_OFFSETX = "OffsetX";
		private static final String XMLKEY_OFFSETY = "OffsetY";
		private static final String XMLKEY_OFFSETZ = "OffsetZ";
		private static final String XMLKEY_SCALEX = "ScaleX";
		private static final String XMLKEY_SCALEY = "ScaleY";
		private static final String XMLKEY_SCALEZ = "ScaleZ";
		private static final String XMLKEY_QUATX = "QuatX";
		private static final String XMLKEY_QUATY = "QuatY";
		private static final String XMLKEY_QUATZ = "QuatZ";
		private static final String XMLKEY_QUATW = "QuatW";

		public int slotHash;
		public float offsetX;
		public float offsetY;
		public float offsetZ;
		public float scaleX;
		public float scaleY;
		public float scaleZ;
		public float quatX;
		public float quatY;
		public float quatZ;
		public float quatW;
	
		private String xmlNodeName;
		private int baseSize;
	
		public BoneDelta() {
			xmlNodeName = "BoneDelta";
			baseSize = 44;
		}
		
		/*----- Read -----*/
		
		protected boolean readBinary_internal(BufferReference dat) {
			if(dat == null) return false;
			
			slotHash = dat.nextInt();
			offsetX = Float.intBitsToFloat(dat.nextInt());
			offsetY = Float.intBitsToFloat(dat.nextInt());
			offsetZ = Float.intBitsToFloat(dat.nextInt());
			scaleX = Float.intBitsToFloat(dat.nextInt());
			scaleY = Float.intBitsToFloat(dat.nextInt());
			scaleZ = Float.intBitsToFloat(dat.nextInt());
			quatX = Float.intBitsToFloat(dat.nextInt());
			quatY = Float.intBitsToFloat(dat.nextInt());
			quatZ = Float.intBitsToFloat(dat.nextInt());
			quatW = Float.intBitsToFloat(dat.nextInt());

			return true;
		}
		
		protected boolean readXMLNode_internal(Element xml_element) {
			if(xml_element == null) return false;
			String nn = xml_element.getNodeName();
			if(nn == null) return false;
			if(!nn.equals(xmlNodeName)) return false;
			
			String aval = null;
			aval = xml_element.getAttribute(XMLKEY_SLOTHASH);
			if(aval != null) slotHash = StringUtils.parseUnsignedInt(aval);
			aval = xml_element.getAttribute(XMLKEY_OFFSETX);
			if(aval != null) offsetX = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_OFFSETY);
			if(aval != null) offsetY = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_OFFSETZ);
			if(aval != null) offsetZ = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_SCALEX);
			if(aval != null) scaleX = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_SCALEY);
			if(aval != null) scaleY = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_SCALEZ);
			if(aval != null) scaleZ = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_QUATX);
			if(aval != null) quatX = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_QUATY);
			if(aval != null) quatY = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_QUATZ);
			if(aval != null) quatZ = (float)Double.parseDouble(aval);
			aval = xml_element.getAttribute(XMLKEY_QUATW);
			if(aval != null) quatW = (float)Double.parseDouble(aval);

			return true;
		}
		
		public static BoneDelta readBinary(BufferReference dat) {
			if(dat == null) return null;
			BoneDelta str = new BoneDelta();
			if(!str.readBinary_internal(dat)) return null;
			return str;
		}
		
		public static BoneDelta readXMLNode(Element xml_element) {
			if(xml_element == null) return null;
			BoneDelta str = new BoneDelta();
			if(!str.readXMLNode_internal(xml_element)) return null;
			return str;
		}
		
		/*----- Write -----*/
		
		public int getBinarySize() {
			int size = baseSize;
			return size;
		}
		
		public FileBuffer writeBinary(boolean byteOrder) {
			FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
			writeBinaryTo(buff);
			return buff;
		}
		
		public int writeBinaryTo(FileBuffer target) {
			if(target == null) return 0;
			long stPos = target.getFileSize();
			
			target.addToFile(slotHash);
			target.addToFile(Float.floatToRawIntBits(offsetX));
			target.addToFile(Float.floatToRawIntBits(offsetY));
			target.addToFile(Float.floatToRawIntBits(offsetZ));
			target.addToFile(Float.floatToRawIntBits(scaleX));
			target.addToFile(Float.floatToRawIntBits(scaleY));
			target.addToFile(Float.floatToRawIntBits(scaleZ));
			target.addToFile(Float.floatToRawIntBits(quatX));
			target.addToFile(Float.floatToRawIntBits(quatY));
			target.addToFile(Float.floatToRawIntBits(quatZ));
			target.addToFile(Float.floatToRawIntBits(quatW));

			return (int)(target.getFileSize() - stPos);
		}
	
		public void writeXMLNode(Writer out, String indent) throws IOException {
			writeXMLNode(out, indent, null);
		}
		
		public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
			if(out == null) return;
			if(indent == null) indent = "";
			
			out.write(indent);
			out.write(String.format("<%s", xmlNodeName));
			if(varName != null){
				out.write(String.format(" VarName=\"%s\"", varName));
			}
			out.write(String.format(" %s=\"0x%08x\"", XMLKEY_SLOTHASH, slotHash));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_OFFSETX, offsetX));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_OFFSETY, offsetY));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_OFFSETZ, offsetZ));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_SCALEX, scaleX));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_SCALEY, scaleY));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_SCALEZ, scaleZ));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_QUATX, quatX));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_QUATY, quatY));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_QUATZ, quatZ));
			out.write(String.format(" %s=\"%.3f\"", XMLKEY_QUATW, quatW));
			out.write("/>\n");

		}
	
	}

	/*----- Read -----*/
	
	protected boolean readBinary_internal(BufferReference dat) {
		if(dat == null) return false;
		
		fileVersion = dat.nextInt();
		entryCount = dat.nextInt();
		entries.ensureCapacity(entryCount);
		for(int i = 0; i < entryCount; i++){
			BoneDelta entry = BoneDelta.readBinary(dat);
			if(entry != null) entries.add(entry);
		}

		return true;
	}
	
	protected boolean readXMLNode_internal(Element xml_element) {
		if(xml_element == null) return false;
		String nn = xml_element.getNodeName();
		if(nn == null) return false;
		if(!nn.equals(xmlNodeName)) return false;
		
		String aval = null;
		Element child = null;
		aval = xml_element.getAttribute(XMLKEY_FILEVERSION);
		if(aval != null) fileVersion = StringUtils.parseSignedInt(aval);
		//aval = xml_element.getAttribute(XMLKEY_ENTRYCOUNT);
		//if(aval != null) entryCount = StringUtils.parseSignedInt(aval);
		
		child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "List", "VarName", XMLKEY_ENTRIES);
		if(child != null){
			List<Element> gclist = XMLReader.getChildElementsWithTag(child, "BoneDelta");
			entryCount = gclist.size();
			if(entryCount > 0) {
				entries.ensureCapacity(entryCount);
				for(Element gc : gclist){
					entries.add(BoneDelta.readXMLNode(gc));
				}	
			}
		}

		return true;
	}
	
	public static BoneDeltaRes readBinary(BufferReference dat) {
		if(dat == null) return null;
		BoneDeltaRes str = new BoneDeltaRes();
		if(!str.readBinary_internal(dat)) return null;
		return str;
	}
	
	public static BoneDeltaRes readXMLNode(Element xml_element) {
		if(xml_element == null) return null;
		BoneDeltaRes str = new BoneDeltaRes();
		if(!str.readXMLNode_internal(xml_element)) return null;
		return str;
	}
	
	/*----- Write -----*/
	
	public int getBinarySize() {
		int size = baseSize;
		for(BoneDelta entries : entries){
			size += entries.getBinarySize();
		}
		return size;
	}
	
	public FileBuffer writeBinary(boolean byteOrder) {
		FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
		writeBinaryTo(buff);
		return buff;
	}
	
	public int writeBinaryTo(FileBuffer target) {
		if(target == null) return 0;
		long stPos = target.getFileSize();
		
		entryCount = entries.size();
		target.addToFile(fileVersion);
		target.addToFile(entryCount);
		for(BoneDelta entries : entries){
			entries.writeBinaryTo(target);
		}

		return (int)(target.getFileSize() - stPos);
	}

	public void writeXMLNode(Writer out, String indent) throws IOException {
		writeXMLNode(out, indent, null);
	}
	
	public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
		if(out == null) return;
		if(indent == null) indent = "";
		
		entryCount = entries.size();
		out.write(indent);
		out.write(String.format("<%s", xmlNodeName));
		if(varName != null){
			out.write(String.format(" VarName=\"%s\"", varName));
		}
		out.write(String.format(" %s=\"%d\"", XMLKEY_FILEVERSION, fileVersion));
		//out.write(String.format(" %s=\"%d\"", XMLKEY_ENTRYCOUNT, entryCount));
		out.write(">\n");
		out.write(indent + "\t<List ");
		out.write(String.format(" VarName=\"%s\">\n", XMLKEY_ENTRIES));
		for(BoneDelta entries : entries){
			entries.writeXMLNode(out, indent + "\t\t", null);
		}
		out.write(indent + "\t</List>\n");
		out.write(indent);
		out.write(String.format("</%s>\n", xmlNodeName));

	}

}
