/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Sat, 18 Jan 2025 21:02:33 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.res.gfx;

import java.io.IOException;
import java.io.Writer;

import org.w3c.dom.Element;

import waffleoRai_Files.XMLReader;
import waffleoRai_Utils.BufferReference;
import waffleoRai_Utils.FileBuffer;
import waffleoRai_Utils.StringUtils;

public class MaterialDefinition{
	
	public static final int DEFO_WRITE_VER = 0x103;
	
	public static final String XML_NODE_NAME = "MaterialDefinition";
	public static final int BASE_SIZE = 20;

	//private static final String XMLKEY_MAGICNO = "MagicNo";
	//private static final String XMLKEY_FILEVERSION = "FileVersion";
	private static final String XMLKEY_MATERIALNAMEHASH = "MaterialNameHash";
	private static final String XMLKEY_SHADERNAMEHASH = "ShaderNameHash";
	//private static final String XMLKEY_DATASIZE = "DataSize";
	private static final String XMLKEY_MATDATA = "MatData";

	public byte[] magicNo;
	//public int fileVersion;
	public int materialNameHash;
	public int shaderNameHash;
	//public int dataSize;
	
	public MTRLBlock dataMTRL;
	public MTNFBlock dataMTNF;

	public MaterialDefinition() {}
	
	/*----- Inner Classes -----*/

	public static class MTRLBlock{
		
		public static final String XML_NODE_NAME = "MTRLBlock";
		public static final int BASE_SIZE = 12;

		private static final String XMLKEY_UNKA = "UnkA";
		private static final String XMLKEY_UNKB = "UnkB";
		private static final String XMLKEY_UNKC = "UnkC";
		private static final String XMLKEY_MATDATA = "MatData";

		public byte[] blockMagicNo = {(byte)'M', (byte)'T', (byte)'R', (byte)'L'};
		public int unkA;
		public short unkB;
		public short unkC;
		public MaterialData matData;
	
		public MTRLBlock() {}
		
		/*----- Read -----*/
		
		protected boolean readBinary_internal(BufferReference dat) {
			if(dat == null) return false;
			
			blockMagicNo = new byte[4];
			for(int i = 0; i < 4; i++){
				blockMagicNo[i] = dat.nextByte();
			}
			unkA = dat.nextInt();
			unkB = dat.nextShort();
			unkC = dat.nextShort();
			matData = MaterialData.readBinary(dat);

			return true;
		}
		
		protected boolean readXMLNode_internal(Element xml_element) {
			if(xml_element == null) return false;
			String nn = xml_element.getNodeName();
			if(nn == null) return false;
			if(!nn.equals(XML_NODE_NAME)) return false;
			
			String aval = null;
			Element child = null;
			aval = xml_element.getAttribute(XMLKEY_UNKA);
			if(aval != null) unkA = StringUtils.parseUnsignedInt(aval);
			aval = xml_element.getAttribute(XMLKEY_UNKB);
			if(aval != null) unkB = (short)StringUtils.parseUnsignedInt(aval);
			aval = xml_element.getAttribute(XMLKEY_UNKC);
			if(aval != null) unkC = (short)StringUtils.parseUnsignedInt(aval);
			child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "MaterialData", "VarName", XMLKEY_MATDATA);
			if(child != null) matData = MaterialData.readXMLNode(child);

			return true;
		}
		
		public static MTRLBlock readBinary(BufferReference dat) {
			if(dat == null) return null;
			MTRLBlock str = new MTRLBlock();
			if(!str.readBinary_internal(dat)) return null;
			return str;
		}
		
		public static MTRLBlock readXMLNode(Element xml_element) {
			if(xml_element == null) return null;
			MTRLBlock str = new MTRLBlock();
			if(!str.readXMLNode_internal(xml_element)) return null;
			return str;
		}
		
		/*----- Write -----*/
		
		public int getBinarySize() {
			int size = BASE_SIZE;
			size += matData.getBinarySize();
			return size;
		}
		
		public FileBuffer writeBinary(boolean byteOrder) {
			FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
			writeBinaryTo(buff);
			return buff;
		}
		
		public int writeBinaryTo(FileBuffer target) {
			if(target == null) return 0;
			long stPos = target.getFileSize();
			
			target.printASCIIToFile("MTRL");
			target.addToFile(unkA);
			target.addToFile(unkB);
			target.addToFile(unkC);
			matData.writeBinaryTo(target, BASE_SIZE);

			return (int)(target.getFileSize() - stPos);
		}
	
		public void writeXMLNode(Writer out, String indent) throws IOException {
			writeXMLNode(out, indent, null);
		}
		
		public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
			if(out == null) return;
			if(indent == null) indent = "";
			
			out.write(indent);
			out.write(String.format("<%s", XML_NODE_NAME));
			if(varName != null){
				out.write(String.format(" VarName=\"%s\"", varName));
			}
			out.write(String.format(" %s=\"0x%08x\"", XMLKEY_UNKA, unkA));
			out.write(String.format(" %s=\"0x%04x\"", XMLKEY_UNKB, unkB));
			out.write(String.format(" %s=\"0x%04x\"", XMLKEY_UNKC, unkC));
			out.write(">\n");
			matData.writeXMLNode(out, indent + "\t", XMLKEY_MATDATA);
			out.write(indent);
			out.write(String.format("</%s>\n", XML_NODE_NAME));

		}
	
	}

	public static class MTNFBlock{
		
		public static final String XML_NODE_NAME = "MTNFBlock";
		public static final int BASE_SIZE = 8;

		private static final String XMLKEY_ISVIDEOSURFACE = "IsVideoSurface";
		private static final String XMLKEY_ISPAINTINGSURFACE = "IsPaintingSurface";
		private static final String XMLKEY_MATINFO = "MatInfo";

		public int isVideoSurface;
		public int isPaintingSurface;
		public MaterialInfo matInfo;
	
		public MTNFBlock() {}
		
		/*----- Read -----*/
		
		protected boolean readBinary_internal(BufferReference dat) {
			if(dat == null) return false;
			
			isVideoSurface = dat.nextInt();
			isPaintingSurface = dat.nextInt();
			matInfo = MaterialInfo.readBinary(dat);

			return true;
		}
		
		protected boolean readXMLNode_internal(Element xml_element) {
			if(xml_element == null) return false;
			String nn = xml_element.getNodeName();
			if(nn == null) return false;
			if(!nn.equals(XML_NODE_NAME)) return false;
			
			String aval = null;
			Element child = null;
			aval = xml_element.getAttribute(XMLKEY_ISVIDEOSURFACE);
			if(aval != null) isVideoSurface = StringUtils.parseUnsignedInt(aval);
			aval = xml_element.getAttribute(XMLKEY_ISPAINTINGSURFACE);
			if(aval != null) isPaintingSurface = StringUtils.parseUnsignedInt(aval);
			child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "MaterialInfo", "VarName", XMLKEY_MATINFO);
			if(child != null) matInfo = MaterialInfo.readXMLNode(child);

			return true;
		}
		
		public static MTNFBlock readBinary(BufferReference dat) {
			if(dat == null) return null;
			MTNFBlock str = new MTNFBlock();
			if(!str.readBinary_internal(dat)) return null;
			return str;
		}
		
		public static MTNFBlock readXMLNode(Element xml_element) {
			if(xml_element == null) return null;
			MTNFBlock str = new MTNFBlock();
			if(!str.readXMLNode_internal(xml_element)) return null;
			return str;
		}
		
		/*----- Write -----*/
		
		public int getBinarySize() {
			int size = BASE_SIZE;
			size += matInfo.getBinarySize();
			return size;
		}
		
		public FileBuffer writeBinary(boolean byteOrder) {
			FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
			writeBinaryTo(buff);
			return buff;
		}
		
		public int writeBinaryTo(FileBuffer target) {
			if(target == null) return 0;
			long stPos = target.getFileSize();
			
			target.addToFile(isVideoSurface);
			target.addToFile(isPaintingSurface);
			matInfo.writeBinaryTo(target);

			return (int)(target.getFileSize() - stPos);
		}
	
		public void writeXMLNode(Writer out, String indent) throws IOException {
			writeXMLNode(out, indent, null);
		}
		
		public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
			if(out == null) return;
			if(indent == null) indent = "";
			
			out.write(indent);
			out.write(String.format("<%s", XML_NODE_NAME));
			if(varName != null){
				out.write(String.format(" VarName=\"%s\"", varName));
			}
			out.write(String.format(" %s=\"0x%08x\"", XMLKEY_ISVIDEOSURFACE, isVideoSurface));
			out.write(String.format(" %s=\"0x%08x\"", XMLKEY_ISPAINTINGSURFACE, isPaintingSurface));
			out.write(">\n");
			matInfo.writeXMLNode(out, indent + "\t", XMLKEY_MATINFO);
			out.write(indent);
			out.write(String.format("</%s>\n", XML_NODE_NAME));
		}
	
	}

	/*----- Read -----*/
	
	protected boolean readBinary_internal(BufferReference dat) {
		if(dat == null) return false;
		
		magicNo = new byte[4];
		for(int i = 0; i < 4; i++){
			magicNo[i] = dat.nextByte();
		}
		int fileVersion = dat.nextInt();
		materialNameHash = dat.nextInt();
		shaderNameHash = dat.nextInt();
		dat.add(4L); //dataSize = dat.nextInt();
		if(fileVersion >= 0x103) dataMTNF = MTNFBlock.readBinary(dat);
		else dataMTRL = MTRLBlock.readBinary(dat);

		return true;
	}
	
	protected boolean readXMLNode_internal(Element xml_element) {
		if(xml_element == null) return false;
		String nn = xml_element.getNodeName();
		if(nn == null) return false;
		if(!nn.equals(XML_NODE_NAME)) return false;
		
		String aval = null;
		Element child = null;

		//aval = xml_element.getAttribute(XMLKEY_FILEVERSION);
		//if(aval != null) fileVersion = StringUtils.parseSignedInt(aval);
		aval = xml_element.getAttribute(XMLKEY_MATERIALNAMEHASH);
		if(aval != null) materialNameHash = StringUtils.parseUnsignedInt(aval);
		aval = xml_element.getAttribute(XMLKEY_SHADERNAMEHASH);
		if(aval != null) shaderNameHash = StringUtils.parseUnsignedInt(aval);
		//aval = xml_element.getAttribute(XMLKEY_DATASIZE);
		//if(aval != null) dataSize = StringUtils.parseUnsignedInt(aval);
		
		//Look for MTNF block. If not there, try MTRL
		child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, MTNFBlock.XML_NODE_NAME, "VarName", XMLKEY_MATDATA);
		if(child != null) dataMTNF = MTNFBlock.readXMLNode(child);
		else {
			child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, MTRLBlock.XML_NODE_NAME, "VarName", XMLKEY_MATDATA);
			if(child != null) dataMTRL = MTRLBlock.readXMLNode(child);
		}

		return true;
	}
	
	public static MaterialDefinition readBinary(BufferReference dat) {
		if(dat == null) return null;
		MaterialDefinition str = new MaterialDefinition();
		if(!str.readBinary_internal(dat)) return null;
		return str;
	}
	
	public static MaterialDefinition readXMLNode(Element xml_element) {
		if(xml_element == null) return null;
		MaterialDefinition str = new MaterialDefinition();
		if(!str.readXMLNode_internal(xml_element)) return null;
		return str;
	}
	
	/*----- Write -----*/
	
	public int getBinarySize() {
		int size = BASE_SIZE;
		if(dataMTNF != null) size += dataMTNF.getBinarySize();
		else if(dataMTRL != null) size += dataMTRL.getBinarySize();
		return size;
	}
	
	public FileBuffer writeBinary(boolean byteOrder, int fileVersion) {
		FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
		writeBinaryTo(buff, fileVersion);
		return buff;
	}
	
	public int writeBinaryTo(FileBuffer target, int fileVersion) {
		if(target == null) return 0;
		long stPos = target.getFileSize();
		
		for(int i = 0; i < 4; i++){
			target.addToFile(magicNo[i]);
		}
		target.addToFile(fileVersion);
		target.addToFile(materialNameHash);
		target.addToFile(shaderNameHash);
		
		if(dataMTNF != null && (fileVersion >= 0x103)) {
			int dataSize = dataMTNF.getBinarySize() - 12;
			target.addToFile(dataSize);
			dataMTNF.writeBinaryTo(target);
		}
		else if(dataMTRL != null && (fileVersion <= 0x102)) {
			int dataSize = dataMTRL.getBinarySize() - 4;
			target.addToFile(dataSize);
			dataMTRL.writeBinaryTo(target);
		}
		else target.addToFile(0);
		
		return (int)(target.getFileSize() - stPos);
	}

	public void writeXMLNode(Writer out, String indent) throws IOException {
		writeXMLNode(out, indent, null);
	}
	
	public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
		if(out == null) return;
		if(indent == null) indent = "";
		
		out.write(indent);
		out.write(String.format("<%s", XML_NODE_NAME));
		if(varName != null){
			out.write(String.format(" VarName=\"%s\"", varName));
		}
		//out.write(String.format(" %s=\"%d\"", XMLKEY_FILEVERSION, fileVersion));
		out.write(String.format(" %s=\"0x%08x\"", XMLKEY_MATERIALNAMEHASH, materialNameHash));
		out.write(String.format(" %s=\"0x%08x\"", XMLKEY_SHADERNAMEHASH, shaderNameHash));
		//out.write(String.format(" %s=\"0x%08x\"", XMLKEY_DATASIZE, dataSize));
		out.write(">\n");
		if(dataMTNF != null) dataMTNF.writeXMLNode(out, indent + "\t", XMLKEY_MATDATA);
		else if(dataMTRL != null) dataMTRL.writeXMLNode(out, indent + "\t", XMLKEY_MATDATA);
		out.write(indent);
		out.write(String.format("</%s>\n", XML_NODE_NAME));
	}

}
