/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Fri, 17 Jan 2025 16:27:12 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.res.gfx;

import java.io.IOException;
import java.io.Writer;

import org.w3c.dom.Element;

import waffleoRai_Files.XMLReader;
import waffleoRai_Files.maxis.res.RCOLHeader;
import waffleoRai_Utils.BufferReference;
import waffleoRai_Utils.FileBuffer;

public class VPXYFile{
//TS3 Script: 

	private static final String XMLKEY_RCOLHEADER = "RcolHeader";
	private static final String XMLKEY_VPXYDATA = "VpxyData";

	public RCOLHeader rcolHeader;
	public VisualProxy vpxyData;
	
	private String xmlNodeName;
	private int baseSize;

	public VPXYFile() {
		xmlNodeName = "VPXYFile";
		baseSize = 0;
	}
	
	/*----- Read -----*/
	
	protected boolean readBinary_internal(BufferReference dat) {
		if(dat == null) return false;
		rcolHeader = RCOLHeader.readBinary(dat);
		vpxyData = VisualProxy.readBinary(dat);
		return true;
	}
	
	protected boolean readXMLNode_internal(Element xml_element) {
		if(xml_element == null) return false;
		String nn = xml_element.getNodeName();
		if(nn == null) return false;
		if(!nn.equals(xmlNodeName)) return false;
		
		Element child = null;
		child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "RCOLHeader", "VarName", XMLKEY_RCOLHEADER);
		if(child != null) rcolHeader = RCOLHeader.readXMLNode(child);
		child = XMLReader.getFirstChildElementWithTagAndAttribute(xml_element, "VisualProxy", "VarName", XMLKEY_VPXYDATA);
		if(child != null) vpxyData = VisualProxy.readXMLNode(child);

		return true;
	}
	
	public static VPXYFile readBinary(BufferReference dat) {
		if(dat == null) return null;
		VPXYFile str = new VPXYFile();
		if(!str.readBinary_internal(dat)) return null;
		return str;
	}
	
	public static VPXYFile readXMLNode(Element xml_element) {
		if(xml_element == null) return null;
		VPXYFile str = new VPXYFile();
		if(!str.readXMLNode_internal(xml_element)) return null;
		return str;
	}
	
	/*----- Write -----*/
	
	public int getBinarySize() {
		int size = baseSize;
		size += rcolHeader.getBinarySize();
		size += vpxyData.getBinarySize();
		return size;
	}
	
	public FileBuffer writeBinary(boolean byteOrder) {
		FileBuffer buff = new FileBuffer(getBinarySize(), byteOrder);
		writeBinaryTo(buff);
		return buff;
	}
	
	public int writeBinaryTo(FileBuffer target) {
		if(target == null) return 0;
		long stPos = target.getFileSize();
		rcolHeader.writeBinaryTo(target);
		vpxyData.writeBinaryTo(target);
		return (int)(target.getFileSize() - stPos);
	}

	public void writeXMLNode(Writer out, String indent) throws IOException {
		writeXMLNode(out, indent, null);
	}
	
	public void writeXMLNode(Writer out, String indent, String varName) throws IOException {
		if(out == null) return;
		if(indent == null) indent = "";
		
		out.write(indent);
		out.write(String.format("<%s", xmlNodeName));
		if(varName != null){
			out.write(String.format(" VarName=\"%s\"", varName));
		}
		out.write(">\n");
		rcolHeader.writeXMLNode(out, indent + "\t", XMLKEY_RCOLHEADER);
		vpxyData.writeXMLNode(out, indent + "\t", XMLKEY_VPXYDATA);
		out.write(indent);
		out.write(String.format("</%s>\n", xmlNodeName));

	}

}
