/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Wed, 1 Jan 2025 17:49:10 -0600
 *-----------------------------------------------------*/

package waffleoRai_Containers.maxis.ts3.savefmts.sim;

import waffleoRai_DataContainers.EnumStringMapper64;

public class ServiceType {
//Game Script: 
//Enum type: u64

	public static final long None = 0x00000000L;
	public static final long Maid = 0x00000001L;
	public static final long PizzaDelivery = 0x00000002L;
	public static final long Babysitter = 0x00000004L;
	public static final long Repairman = 0x00000008L;
	public static final long Burglar = 0x00000010L;
	public static final long FakeMetaAutonomy = 0x00000020L;
	public static final long NewspaperDelivery = 0x00000040L;
	public static final long MailCarrier = 0x00000080L;
	public static final long GrimReaper = 0x00000100L;
	public static final long Police = 0x00000200L;
	public static final long Repoman = 0x00000400L;
	public static final long Firefighter = 0x00000800L;
	public static final long SocialWorkerChildProtection = 0x00001000L;
	public static final long SocialWorkerAdoption = 0x00002000L;
	public static final long Magician = 0x00004000L;
	public static final long ScienceGeek = 0x00008000L;
	public static final long TutorialNpcFisherman = 0x00010000L;
	public static final long TutorialNpcBugCollector = 0x00020000L;
	public static final long TutorialNpcSeedCollector = 0x00040000L;
	public static final long TutorialNpcGemCollector = 0x00080000L;
	public static final long Butler = 0x00100000L;
	public static final long Bartender = 0x00200000L;
	public static final long Dancer = 0x00400000L;
	public static final long SocialWorkerPetPutUp = 0x00800000L;
	public static final long SocialWorkerPetAdoption = 0x01000000L;
	public static final long SingAGram = 0x02000000L;
	public static final long Singer = 0x04000000L;
	public static final long PerformanceArtist = 0x08000000L;
	public static final long DJ = 0x10000000L;
	public static final long UniversityMascot = 0x20000000L;
	public static final long Resortworker = 0x40000000L;
	public static final long ResortMaintenanceLow = 0x80000000L;
	public static final long ResortMaintenanceMedium = 0x100000000L;
	public static final long ResortMaintenanceHigh = 0x200000000L;
	public static final long ResortworkerBar = 0x400000000L;
	public static final long TimeTraveler = 0x800000000L;
	public static final long ChildCareServices = 0x00100004L;
	public static final long CleaningServices = 0x00100001L;

	public static final long[] ALL_VALUES = {
		0x00000000L, 0x00000001L, 0x00000002L, 0x00000004L, 
		0x00000008L, 0x00000010L, 0x00000020L, 0x00000040L, 
		0x00000080L, 0x00000100L, 0x00000200L, 0x00000400L, 
		0x00000800L, 0x00001000L, 0x00002000L, 0x00004000L, 
		0x00008000L, 0x00010000L, 0x00020000L, 0x00040000L, 
		0x00080000L, 0x00100000L, 0x00200000L, 0x00400000L, 
		0x00800000L, 0x01000000L, 0x02000000L, 0x04000000L, 
		0x08000000L, 0x10000000L, 0x20000000L, 0x40000000L, 
		0x80000000L, 0x100000000L, 0x200000000L, 0x400000000L, 
		0x800000000L, 0x00100004L, 0x00100001L
	};

	public static final String[] ALL_NAMES = {
		"None", "Maid", "PizzaDelivery", "Babysitter", 
		"Repairman", "Burglar", "FakeMetaAutonomy", "NewspaperDelivery", 
		"MailCarrier", "GrimReaper", "Police", "Repoman", 
		"Firefighter", "SocialWorkerChildProtection", "SocialWorkerAdoption", "Magician", 
		"ScienceGeek", "TutorialNpcFisherman", "TutorialNpcBugCollector", "TutorialNpcSeedCollector", 
		"TutorialNpcGemCollector", "Butler", "Bartender", "Dancer", 
		"SocialWorkerPetPutUp", "SocialWorkerPetAdoption", "SingAGram", "Singer", 
		"PerformanceArtist", "DJ", "UniversityMascot", "Resortworker", 
		"ResortMaintenanceLow", "ResortMaintenanceMedium", "ResortMaintenanceHigh", "ResortworkerBar", 
		"TimeTraveler", "ChildCareServices", "CleaningServices"
	};

	private static EnumStringMapper64 mapper;

	public static String stringFromValue(long value){
		if(mapper == null){
			mapper = new EnumStringMapper64(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValueFlags(value);
	}

	public static long valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper64(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromStringFlags(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
