/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Wed, 1 Jan 2025 00:31:43 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.ts3enum;

import java.util.Map;
import java.util.HashMap;

public class DeathType {
//Game Script: 
//Enum type: u32

	public static final int None = 0x00000000;
	public static final int OldAge = 0x00000001;
	public static final int Drown = 0x00000002;
	public static final int Starve = 0x00000003;
	public static final int Electrocution = 0x00000004;
	public static final int Burn = 0x00000005;
	public static final int MummyCurse = 0x00000006;
	public static final int Meteor = 0x00000007;
	public static final int Thirst = 0x00000008;
	public static final int PetOldAgeGood = 0x00000009;
	public static final int PetOldAgeBad = 0x0000000A;
	public static final int InvisibleSim = 0x0000000B;
	public static final int WateryGrave = 0x0000000C;
	public static final int HumanStatue = 0x0000000D;
	public static final int Transmuted = 0x0000000E;
	public static final int HauntingCurse = 0x0000000F;
	public static final int JellyBeanDeath = 0x00000010;
	public static final int Freeze = 0x00000011;
	public static final int BluntForceTrauma = 0x00000012;
	public static final int Ranting = 0x00000013;
	public static final int Shark = 0x00000014;
	public static final int ScubaDrown = 0x00000015;
	public static final int MermaidDehydrated = 0x00000016;
	public static final int Robot = 0x00000017;
	public static final int Causality = 0x00000018;
	public static final int Jetpack = 0x00000019;
	public static final int FutureUrnstoneHologram = 0x0000001A;

	public static final int[] ALL_VALUES = {
		0x00000000, 0x00000001, 0x00000002, 0x00000003, 0x00000004, 0x00000005, 0x00000006, 0x00000007, 
		0x00000008, 0x00000009, 0x0000000A, 0x0000000B, 0x0000000C, 0x0000000D, 0x0000000E, 0x0000000F, 
		0x00000010, 0x00000011, 0x00000012, 0x00000013, 0x00000014, 0x00000015, 0x00000016, 0x00000017, 
		0x00000018, 0x00000019, 0x0000001A
	};

	public static final String[] ALL_NAMES = {
		"None", "OldAge", "Drown", "Starve", 
		"Electrocution", "Burn", "MummyCurse", "Meteor", 
		"Thirst", "PetOldAgeGood", "PetOldAgeBad", "InvisibleSim", 
		"WateryGrave", "HumanStatue", "Transmuted", "HauntingCurse", 
		"JellyBeanDeath", "Freeze", "BluntForceTrauma", "Ranting", 
		"Shark", "ScubaDrown", "MermaidDehydrated", "Robot", 
		"Causality", "Jetpack", "FutureUrnstoneHologram"
	};

	private static Map<String, Integer> nameMap;
	private static Map<Integer, String> valMap;

	public static String stringFromValue(int value){
		if(valMap == null){
			valMap = new HashMap<Integer, String>();
			for(int i = 0; i < ALL_VALUES.length; i++){
				valMap.put(ALL_VALUES[i], ALL_NAMES[i]);
			}
		}
		return valMap.get(value);
	}

	public static int valueFromString(String str){
		if(nameMap == null){
			nameMap = new HashMap<String, Integer>();
			for(int i = 0; i < ALL_NAMES.length; i++){
				nameMap.put(ALL_NAMES[i], ALL_VALUES[i]);
			}
		}
		Integer mappedVal = nameMap.get(str);
		if(mappedVal == null) return -1;
		return mappedVal;
	}

	public static void disposeMaps(){
		if(nameMap != null){
			nameMap.clear();
			nameMap = null;
		}
		if(valMap != null){
			valMap.clear();
			valMap = null;
		}
	}
}
