/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Sun, 26 Jan 2025 17:16:42 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.ts3enum;

import waffleoRai_DataContainers.EnumStringMapper32;

public class OutfitCategories {
//Game Script: 
//Enum type: u32

	public static final int None = 0x00000000;
	public static final int Naked = 0x00000001;
	public static final int Everyday = 0x00000002;
	public static final int Formalwear = 0x00000004;
	public static final int Sleepwear = 0x00000008;
	public static final int Swimwear = 0x00000010;
	public static final int Athletic = 0x00000020;
	public static final int Singed = 0x00000040;
	public static final int MartialArts = 0x00000080;
	public static final int Career = 0x00000100;
	public static final int AuxCareer = 0x00000200;
	public static final int Makeover = 0x00000400;
	public static final int SkinnyDippingTowel = 0x00000800;
	public static final int Racing = 0x00001000;
	public static final int Jumping = 0x00002000;
	public static final int Bridle = 0x00004000;
	public static final int Markings = 0x00007000;
	public static final int Massage = 0x00008000;
	public static final int ChildImagination = 0x00010000;
	public static final int Special = 0x00020000;
	public static final int Outerwear = 0x00040000;
	public static final int Supernatural = 0x00080000;
	public static final int CategoryMask = 0x0007FFFF;
	public static final int ValidForMaternity = 0x00100000;
	public static final int ValidForRandom = 0x00200000;
	public static final int IsHat = 0x00400000;
	public static final int IsRevealing = 0x00800000;
	public static final int IsHiddenInCAS = 0x01000000;
	public static final int RegionHead = 0x02000000;
	public static final int RegionChest = 0x04000000;
	public static final int RegionBelly = 0x06000000;
	public static final int RegionBack = 0x08000000;
	public static final int RegionTail = 0x0A000000;
	public static final int RegionFrontLeftLeg = 0x0C000000;
	public static final int RegionFrontRightLeg = 0x0E000000;
	public static final int RegionRearLeftLeg = 0x10000000;
	public static final int RegionRearRightLeg = 0x12000000;
	public static final int RegionAll = 0x14000000;
	public static final int RegionMask = 0x1E000000;
	public static final int All = 0xFFFFFFFF;
	public static final int PrimaryCategories = 0x0000013E;
	public static final int PrimaryHorseCategories = 0x00007002;

	public static final int[] ALL_VALUES = {
		0x00000000, 0x00000001, 0x00000002, 0x00000004, 0x00000008, 0x00000010, 0x00000020, 0x00000040, 
		0x00000080, 0x00000100, 0x00000200, 0x00000400, 0x00000800, 0x00001000, 0x00002000, 0x00004000, 
		0x00007000, 0x00008000, 0x00010000, 0x00020000, 0x00040000, 0x00080000, 0x0007FFFF, 0x00100000, 
		0x00200000, 0x00400000, 0x00800000, 0x01000000, 0x02000000, 0x04000000, 0x06000000, 0x08000000, 
		0x0A000000, 0x0C000000, 0x0E000000, 0x10000000, 0x12000000, 0x14000000, 0x1E000000, 0xFFFFFFFF, 
		0x0000013E, 0x00007002
	};

	public static final String[] ALL_NAMES = {
		"None", "Naked", "Everyday", "Formalwear", 
		"Sleepwear", "Swimwear", "Athletic", "Singed", 
		"MartialArts", "Career", "AuxCareer", "Makeover", 
		"SkinnyDippingTowel", "Racing", "Jumping", "Bridle", 
		"Markings", "Massage", "ChildImagination", "Special", 
		"Outerwear", "Supernatural", "CategoryMask", "ValidForMaternity", 
		"ValidForRandom", "IsHat", "IsRevealing", "IsHiddenInCAS", 
		"RegionHead", "RegionChest", "RegionBelly", "RegionBack", 
		"RegionTail", "RegionFrontLeftLeg", "RegionFrontRightLeg", "RegionRearLeftLeg", 
		"RegionRearRightLeg", "RegionAll", "RegionMask", "All", 
		"PrimaryCategories", "PrimaryHorseCategories"
	};

	private static EnumStringMapper32 mapper;

	public static String stringFromValue(int value){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValueFlags(value);
	}

	public static int valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		Integer n = mapper.valueFromStringFlags(str);
		if(n == null) return 0;
		return n;
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
