/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Wed, 1 Jan 2025 17:27:44 -0600
 *-----------------------------------------------------*/

package waffleoRai_Files.maxis.ts3enum;

import waffleoRai_DataContainers.EnumStringMapper16;

public class RomanceVisibilityStateType {
//Game Script: 
//Enum type: s16

	public static final short None = (short)0x0000;
	public static final short Virtuous = (short)0x0001;
	public static final short Cheating = (short)0x0002;

	public static final short[] ALL_VALUES = {
		(short)0x0000, (short)0x0001, (short)0x0002
	};

	public static final String[] ALL_NAMES = {
		"None", "Virtuous", "Cheating"
	};

	private static EnumStringMapper16 mapper;

	public static String stringFromValue(short value){
		if(mapper == null){
			mapper = new EnumStringMapper16(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValue(value);
	}

	public static short valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper16(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromString(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
