/*-----------------------------------------------------
 * Autogenerated Java class from XML definition.
 * Created Wed, 1 Jan 2025 17:42:15 -0600
 *-----------------------------------------------------*/

package waffleoRai_Containers.maxis.ts3.savefmts.sim.cas;

import waffleoRai_DataContainers.EnumStringMapper32;

public class OutfitCategories {
//Game Script: 
//Enum type: u32

	public static final int None = 0x00000000;
	public static final int Naked = 0x00000001;
	public static final int Everyday = 0x00000002;
	public static final int Formalwear = 0x00000004;
	public static final int Sleepwear = 0x00000008;
	public static final int Swimwear = 0x00000010;
	public static final int Athletic = 0x00000020;
	public static final int Singed = 0x00000040;
	public static final int MartialArts = 0x00000080;
	public static final int Career = 0x00000100;
	public static final int AuxCareer = 0x00000200;
	public static final int Makeover = 0x00000400;
	public static final int SkinnyDippingTowel = 0x00000800;
	public static final int Racing = 0x00001000;
	public static final int Jumping = 0x00002000;
	public static final int Bridle = 0x00004000;
	public static final int Massage = 0x00008000;
	public static final int ChildImagination = 0x00010000;
	public static final int Special = 0x00020000;
	public static final int Outerwear = 0x00040000;
	public static final int Supernatural = 0x00080000;
	public static final int CategoryMask = 0x00100000;
	public static final int All = 0xFFFFFFFF;
	public static final int PrimaryCategories = 0x0000013E;
	public static final int PrimaryHorseCategories = 0x00007002;

	public static final int[] ALL_VALUES = {
		0x00000000, 0x00000001, 0x00000002, 0x00000004, 0x00000008, 0x00000010, 0x00000020, 0x00000040, 
		0x00000080, 0x00000100, 0x00000200, 0x00000400, 0x00000800, 0x00001000, 0x00002000, 0x00004000, 
		0x00008000, 0x00010000, 0x00020000, 0x00040000, 0x00080000, 0x00100000, 0xFFFFFFFF, 0x0000013E, 
		0x00007002
	};

	public static final String[] ALL_NAMES = {
		"None", "Naked", "Everyday", "Formalwear", 
		"Sleepwear", "Swimwear", "Athletic", "Singed", 
		"MartialArts", "Career", "AuxCareer", "Makeover", 
		"SkinnyDippingTowel", "Racing", "Jumping", "Bridle", 
		"Massage", "ChildImagination", "Special", "Outerwear", 
		"Supernatural", "CategoryMask", "All", "PrimaryCategories", 
		"PrimaryHorseCategories"
	};

	private static EnumStringMapper32 mapper;

	public static String stringFromValue(int value){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.stringFromValueFlags(value);
	}

	public static int valueFromString(String str){
		if(mapper == null){
			mapper = new EnumStringMapper32(ALL_VALUES, ALL_NAMES);
		}
		return mapper.valueFromStringFlags(str);
	}

	public static void disposeMaps(){
		if(mapper != null){
			mapper.dispose();
			mapper = null;
		}
	}
}
